services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - 8000:8000
    expose:
      - 80  #  установлен в traefik ?
    networks:
      default:
        aliases:
          - web_internal
      traefik:

    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.bot.entrypoints=https"
      - "traefik.http.routers.bot.rule=Host(`old.kik-soft.ru`)"
      - "traefik.http.routers.bot.tls=true"
      - "traefik.http.routers.bot.tls.certresolver=letsEncrypt"
      - "traefik.http.services.bot-service.loadbalancer.server.port=80"
networks:
  traefik:
    name: traefik
#    external: true
